version: '3.3'

networks:
  www-external:
    internal: false
  www-internal:
    internal: true

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:www-base
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"
  httpd:
    container_name: httpd
    image: httpd:www-base
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "apache:/var/www/html"
      - "./httpd/resources/:/tmp/httpd"
  liferay:
    container_name: liferay
    depends_on:
     - "mariadb"
    env_file:
      - "liferay/liferay.env"
    environment:
      - "LIFERAY_TUNNEL_PERIOD_SERVLET_PERIOD_HOSTS_PERIOD_ALLOWED=127.0.0.1,SERVER_IP,liferay-staging,localhost"
      - "LIFERAY_AXIS_PERIOD_SERVLET_PERIOD_HOSTS_PERIOD_ALLOWED=127.0.0.1,SERVER_IP,192.168.0.16,liferay-staging,localhost"
      - "LIFERAY_TUNNELING_PERIOD_SERVLET_PERIOD_SHARED_PERIOD_SECRET=6162636465666768696a6b6c6d6e6f70"
      - "LIFERAY_TUNNELING_PERIOD_SERVLET_PERIOD_SHARED_PERIOD_SECRET_PERIOD_HEX=true"
      - "LIFERAY_AUTH_PERIOD_VERIFIER_PERIOD_UPPERCASET_UNNELING_UPPERCASES_ERVLET_UPPERCASEA_UTH_UPPERCASEV_ERIFIER_PERIOD_HOSTS_PERIOD_ALLOWED="
    image: liferay:www-base
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "8000:8000"
      - "11311:11311"
      - "12345:12345"
    user: liferay
    volumes:
      - "liferay:/opt/java/liferay/data"
      - "./liferay/resources:/tmp/liferay"
      - "../../extensions/wcm-deployment/wcm-deployment-service/src/main/resources:/mnt/wcm"
      - "./liferay/resources/deploy:/opt/java/liferay/deploy"
      - "./liferay/resources/osgi/modules:/opt/java/liferay/osgi/modules"
      - "./liferay/resources/osgi/war:/opt/java/liferay/osgi/war"
  liferay-staging:
      container_name: liferay-staging
      depends_on:
       - "mariadb-staging"
      env_file:
        - "liferay/liferay.env"
      environment:
        - "LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mariadb://mariadb-staging/lportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false"
        - "LIFERAY_TUNNEL_PERIOD_SERVLET_PERIOD_HOSTS_PERIOD_ALLOWED=127.0.0.1,SERVER_IP,liferay,localhost"
        - "LIFERAY_AXIS_PERIOD_SERVLET_PERIOD_HOSTS_PERIOD_ALLOWED=127.0.0.1,SERVER_IP,192.168.0.16,liferay,localhost"
        - "LIFERAY_TUNNELING_PERIOD_SERVLET_PERIOD_SHARED_PERIOD_SECRET=6162636465666768696a6b6c6d6e6f70"
        - "LIFERAY_TUNNELING_PERIOD_SERVLET_PERIOD_SHARED_PERIOD_SECRET_PERIOD_HEX=true"
        - "LIFERAY_AUTH_PERIOD_VERIFIER_PERIOD_UPPERCASET_UNNELING_UPPERCASES_ERVLET_UPPERCASEA_UTH_UPPERCASEV_ERIFIER_PERIOD_HOSTS_PERIOD_ALLOWED="
      image: liferay:www-base
      networks:
        - "www-external"
        - "www-internal"
      ports:
        - "8001:8000"
        - "8081:8080"
      user: liferay
      volumes:
        - "liferay-staging:/opt/java/liferay/data"
        - "./liferay/resources:/tmp/liferay"
        - "../../extensions/wcm-deployment/wcm-deployment-service/src/main/resources:/mnt/wcm"
        - "./liferay/resources/deploy:/opt/java/liferay/deploy"
        - "./liferay/resources/osgi/modules:/opt/java/liferay/osgi/modules"
  mariadb:
    container_name: mariadb
    env_file:
      - "mariadb/mariadb.env"
    image: mariadb:www-base
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "3307:3306"
    volumes:
      - "mariadb:/var/lib/mysql"
      - "./mariadb/resources:/tmp/mariadb"
  mariadb-staging:
      container_name: mariadb-staging
      env_file:
        - "mariadb/mariadb.env"
      image: mariadb:www-base
      networks:
        - "www-external"
        - "www-internal"
      ports:
        - "3308:3306"
      volumes:
        - "mariadb-staging:/var/lib/mysql"
        - "./mariadb/resources:/tmp/mariadb"
  mockmock:
    build: mockmock/.
    container_name: mockmock
    expose:
      - "25"
    image: mockmock:www-local
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "8282:8282"
    volumes:
      - "mockmock:/home"
  hubspot:
    build: hubspot/.
    container_name: hubspot
    image: hubspot:www-local
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "8080:80"

volumes:
  apache:
  elasticsearch:
  liferay:
  liferay-staging:
  mariadb:
  mariadb-staging:
  mockmock:
