version: '3.3'

networks:
  www-external:
    internal: false
  www-internal:
    internal: true

services:
  liferay:
    build: liferay/.
    container_name: upgrade_liferay
    depends_on:
     - "mariadb"
    command: ["echo", "done"]
    environment:
      - "CATALINA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"
    image: liferay:www-base
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - "liferay:/opt/java/liferay/data"
      - "liferay-tools:/opt/java/liferay/tools"
      - "./liferay/resources:/tmp/liferay"
  mariadb:
    container_name: local_mariadb
    env_file:
          - "mariadb/mariadb.env"
    image: mariadb:www-base
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "3307:3306"
    volumes:
      - "mariadb:/var/lib/mysql"
      - "./mariadb/resources:/tmp/mariadb"

volumes:
  liferay:
  liferay-tools:
  mariadb:
   external:
      name: local_mariadb
