version: '3.3'

networks:
  www-external:
    internal: false
  www-internal:
    internal: true

services:
  upgrade_liferay:
    container_name: upgrade_liferay
    depends_on:
     - "mariadb"
    command: ["echo", "done"]
    env_file:
      - "liferay/liferay.env"
    environment:
      - "CATALINA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n"
    entrypoint: ["/opt/java/liferay/bin/upgradedb.sh"]
    image: liferay:www
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - "upgrade_liferay:/opt/java/liferay/data"
      - "./liferay/resources:/tmp/liferay"
      - "./liferay/resources/bin/upgradedb.sh:/opt/java/liferay/bin/upgradedb.sh"
      - "./liferay/resources/osgi/configs:/opt/java/liferay/osgi/configs"
      - "./liferay/resources/tools:/mnt/upgradetools"
  upgrade_mariadb:
    container_name: upgrade_mariadb
    env_file:
      - "mariadb/mariadb.env"
    image: mariadb:www
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "3307:3306"
    volumes:
      - "upgrade_mariadb:/var/lib/mysql"
      - "./mariadb/resources/etc/mysql/conf.d/local.cnf:/etc/mysql/conf.d/local.cnf"
      - "./mariadb/resources/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/"
volumes:
  upgrade_liferay:
  liferay-tools:
  upgrade_mariadb:
   external:
    name: docker_mariadb
