version: '3.3'

networks:
  www-external:
    internal: false
  www-internal:
    internal: true

services:
  elasticsearch62:
    container_name: elasticsearch62
    environment:
      - "cluster.name=elasticsearch"
    image: elasticsearch:www
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elasticsearch62:/usr/share/elasticsearch/data"
  httpd62:
    container_name: httpd62
    environment:
      - "SERVER_NAME=localhost"
      - "LIFERAY_CONTAINER_NAME=liferay62"
    image: httpd:www
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "httpd62:/var/www/html"
      - "../httpd/resources/:/tmp/httpd"
  liferay62:
    build:
      args:
        JAVA_PACKAGE: openjdk7-jre
        BRANCH: ee-6.2.x
        LIFERAY_DOWNLOAD_URL: http://mirrors/files.liferay.com/private/ee/portal/6.2.10.21/liferay-portal-tomcat-6.2-ee-sp20-20170717160924965.zip
        LIFERAY_FIXPACK_DOWNLOAD_URLS: http://mirrors/files.liferay.com/private/ee/fix-packs/6.2.10/portal/liferay-fix-pack-portal-164-6210.zip
      context: liferay/.
    container_name: liferay62
    depends_on:
     - "mariadb62"
    environment:
      - "VIRTUAL_PORT=8080"
    image: liferay-plugins-62:www
    ports:
      - "8000:8000"
      - "11311:11311"
      - "12345:12345"
    user: liferay
    networks:
      - "www-external"
      - "www-internal"
    volumes:
      - "liferay62:/opt/java/liferay/data"
      - "./liferay/resources/deploy:/opt/java/liferay/deploy"
  mariadb62:
    container_name: mariadb62
    env_file:
      - "mariadb/mariadb.env"
    image: mariadb:www
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "3307:3306"
    volumes:
      - "mariadb62:/var/lib/mysql"
      - "./mariadb/resources/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/"
  hubspot62:
    container_name: hubspot62
    image: hubspot:www
    networks:
      - "www-external"
      - "www-internal"
    ports:
      - "8080:80"
    volumes:
      - "httpd62:/home"

volumes:
  elasticsearch62:
  httpd62:
  hubspot62:
  liferay62:
  mariadb62:
